import { LibraryEntry, MatrixRow, Paper } from '../types';
import { cleanText, formatAuthors } from './cardView';

/**
 * Library exports. Every format is built only from source metadata (title,
 * authors, IDs, URLs). Nothing here is generated by an LLM, so a citation can
 * never point at a paper that does not exist.
 */

export const EMPTY_MATRIX: MatrixRow = { task: '', method: '', data: '', metric: '', result: '', limitation: '' };

export function arxivId(paper: Paper): string | null {
  if (paper.id.startsWith('arxiv:')) return paper.id.slice('arxiv:'.length).replace(/v\d+$/, '');
  const m = (paper.url || '').match(/arxiv\.org\/(?:abs|pdf)\/([^\s?#]+?)(?:v\d+)?(?:\.pdf)?$/);
  return m ? m[1] : null;
}

export function doiOf(paper: Paper): string | null {
  if (paper.doi) return paper.doi.replace(/^https?:\/\/(dx\.)?doi\.org\//i, '');
  const m = (paper.url || '').match(/doi\.org\/(10\.[^\s?#]+)/i);
  return m ? decodeURIComponent(m[1]) : null;
}

function asciiFold(s: string): string {
  return s.normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^A-Za-z0-9]/g, '');
}

function lastName(author: string): string {
  const parts = author.trim().split(/\s+/);
  return parts[parts.length - 1] || 'anon';
}

const STOP = new Set(['a', 'an', 'the', 'on', 'of', 'for', 'in', 'to', 'and', 'with', 'via', 'towards', 'toward']);

/** e.g. "sabour2026patientact"; collisions get a, b, c… suffixes. */
export function citationKeys(papers: Paper[]): Map<string, string> {
  const keys = new Map<string, string>();
  const seen = new Map<string, number>();
  for (const p of papers) {
    const author = asciiFold(lastName(p.authors?.[0] || 'anon')).toLowerCase() || 'anon';
    const year = p.year ? String(p.year) : 'nd';
    const word = cleanText(p.originalTitle)
      .split(/\s+/)
      .map((w) => asciiFold(w).toLowerCase())
      .find((w) => w.length > 2 && !STOP.has(w)) || 'paper';
    const base = `${author}${year}${word}`;
    const n = seen.get(base) || 0;
    seen.set(base, n + 1);
    keys.set(p.id, n === 0 ? base : `${base}${String.fromCharCode(96 + n)}`);
  }
  return keys;
}

const LATEX_ESCAPES: Record<string, string> = {
  '\\': '\\textbackslash{}',
  '&': '\\&',
  '%': '\\%',
  $: '\\$',
  '#': '\\#',
  _: '\\_',
  '{': '\\{',
  '}': '\\}',
  '~': '\\textasciitilde{}',
  '^': '\\textasciicircum{}',
};

/** Escapes LaTeX special characters in one pass (so escapes are not re-escaped). */
export function escapeLatex(s: string): string {
  return s.replace(/[\\&%$#_{}~^]/g, (c) => LATEX_ESCAPES[c]);
}

function bibField(name: string, value: string | null | undefined): string | null {
  if (!value) return null;
  return `  ${name} = {${value}}`;
}

export function toBibTeX(papers: Paper[]): string {
  const keys = citationKeys(papers);
  return papers
    .map((p) => {
      const ax = arxivId(p);
      const doi = doiOf(p);
      const venue = p.venue && !/arxiv preprint/i.test(p.venue) ? p.venue : null;
      const type = venue ? 'article' : 'misc';
      const fields = [
        bibField('title', `{${escapeLatex(cleanText(p.originalTitle))}}`),
        bibField('author', (p.authors || []).map((a) => escapeLatex(a)).join(' and ') || 'Unknown'),
        bibField('year', p.year ? String(p.year) : null),
        venue ? bibField('journal', escapeLatex(venue)) : null,
        ax ? bibField('eprint', ax) : null,
        ax ? bibField('archivePrefix', 'arXiv') : null,
        bibField('doi', doi),
        bibField('url', p.url),
      ].filter(Boolean);
      return `@${type}{${keys.get(p.id)},\n${fields.join(',\n')}\n}`;
    })
    .join('\n\n')
    .concat(papers.length ? '\n' : '');
}

function risLine(tag: string, value: string | null | undefined): string | null {
  if (!value) return null;
  return `${tag}  - ${value.replace(/\r?\n/g, ' ')}`;
}

/** RIS imports into Zotero, Mendeley, EndNote and most reference managers. */
export function toRIS(entries: LibraryEntry[]): string {
  return entries
    .map(({ paper: p, note }) => {
      const venue = p.venue && !/arxiv preprint/i.test(p.venue) ? p.venue : null;
      const lines = [
        risLine('TY', venue ? 'JOUR' : 'GEN'),
        risLine('TI', cleanText(p.originalTitle)),
        ...(p.authors || []).map((a) => risLine('AU', a)),
        risLine('PY', p.year ? String(p.year) : null),
        risLine('T2', venue),
        risLine('DO', doiOf(p)),
        risLine('UR', p.url),
        risLine('AB', cleanText(p.summary)),
        risLine('N1', note || null),
        ...(p.topics || []).map((t) => risLine('KW', t)),
        risLine('DB', p.source),
        'ER  - ',
      ].filter(Boolean);
      return lines.join('\n');
    })
    .join('\n\n')
    .concat(entries.length ? '\n' : '');
}

export function csvCell(value: string | number | null | undefined): string {
  const s = value === null || value === undefined ? '' : String(value);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export const MATRIX_COLUMNS: { key: keyof MatrixRow; label: string }[] = [
  { key: 'task', label: 'Task' },
  { key: 'method', label: 'Method' },
  { key: 'data', label: 'Data' },
  { key: 'metric', label: 'Metric' },
  { key: 'result', label: 'Result' },
  { key: 'limitation', label: 'Limitation' },
];

/** The literature matrix as CSV (opens in Sheets / Excel). */
export function toMatrixCSV(entries: LibraryEntry[]): string {
  const header = ['Title', 'Authors', 'Year', 'Venue', 'URL', ...MATRIX_COLUMNS.map((c) => c.label), 'Note'];
  const rows = entries.map(({ paper: p, matrix, note }) => {
    const m = matrix || p.matrixRow || EMPTY_MATRIX;
    return [
      cleanText(p.originalTitle),
      (p.authors || []).join('; '),
      p.year ?? '',
      p.venue || '',
      p.url,
      ...MATRIX_COLUMNS.map((c) => m[c.key] || ''),
      note || '',
    ];
  });
  return [header, ...rows].map((r) => r.map(csvCell).join(',')).join('\r\n') + '\r\n';
}

/** Markdown for Notion, Obsidian or a lab wiki. */
export function toMarkdown(entries: LibraryEntry[], title = 'Reading list'): string {
  const lines = [`# ${title}`, ''];
  for (const { paper: p, note, matrix } of entries) {
    lines.push(`## ${cleanText(p.headline || p.originalTitle)}`);
    if (p.headline) lines.push(`*${cleanText(p.originalTitle)}*`);
    lines.push(`${formatAuthors(p.authors, p.authorCount)}${p.year ? ` (${p.year})` : ''}. [Link](${p.url})`);
    const m = matrix || p.matrixRow;
    if (m && Object.values(m).some(Boolean)) {
      lines.push('');
      for (const c of MATRIX_COLUMNS) if (m[c.key]) lines.push(`- **${c.label}:** ${m[c.key]}`);
    }
    if (note) lines.push('', `> ${note}`);
    lines.push('');
  }
  return lines.join('\n');
}

/** One-line citation for copying into a message or notes. */
export function shortCitation(p: Paper): string {
  const ax = arxivId(p);
  const doi = doiOf(p);
  const where = doi ? `doi:${doi}` : ax ? `arXiv:${ax}` : p.url;
  return `${formatAuthors(p.authors, p.authorCount)} (${p.year ?? 'n.d.'}). ${cleanText(p.originalTitle)}. ${where}`;
}
